services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - default
      - moodle-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: testlify-lti-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - MONGODB_URI=mongodb://mongo:27017/lti-plugin
      - LTI_KEY=${LTI_KEY}
      - UI_URL=${UI_URL:-http://localhost:3000}
      - TOOL_URL=${TOOL_URL:-http://host.docker.internal:3000}
      - SERVER_URL=${SERVER_URL:-http://localhost:3000}
      - TESTLIFY_TOKEN=${TESTLIFY_TOKEN}
      - LTI_WEBHOOK_SECRET=${LTI_WEBHOOK_SECRET}
    networks:
      - default
      - moodle-net
    depends_on:
      - mongo

networks:
  default:
  moodle-net:
    name: moodle-docker_default
    external: true

volumes:
  mongodata:
